#!/bin/bash

yadm remote set-url origin git@github.com:cohenchris/dotfiles.git
yadm decrypt

################################################################################
#                        INSTALL PERSONAL PACKAGES                             #
################################################################################
# Add a PacMan visual + enable parallel downloads
sudo sed '/ParallelDownloads/s/^#/ILoveCandy\n/g' -i /etc/pacman.conf

paru -Syu --noconfirm
filename="packages"
cd ~/.local/backup/

# install all personal packages
total_pkgs=$(grep '^[a-zA-Z0-9]' packages | wc -l)
echo -e "\nDownloading $total_pkgs personal packages..."
curr_pkg=0

while read pkg_name
do
  # Omit lines that are blank or commented out
  if [[ -n $pkg_name ]] && ! [[ $pkg_name =~ ^#.* ]]; then

    pkg_name=$(echo $pkg_name | cut -d "#" -f 1)

    curr_pkg=$((curr_pkg+1))
    echo "Installing package $curr_pkg/$total_pkgs - $pkg_name"
    paru -S --noconfirm $pkg_name > /dev/null 2>&1

    if [[ $? -ne 0 ]]
    then
      echo $pkg_name >> ~/failed_installs.txt
    fi

  fi
done < $filename
cd

################################################################################
#                             SHELL + TERMINAL                                 #
################################################################################
echo -e "\nConfiguring zsh..."
sudo mkdir /etc/zsh
echo "ZDOTDIR=$HOME/.config/shell" > zshenv
sudo mv zshenv /etc/zsh/

# Change default shell to zsh
chsh -s $(which zsh)

# Install zsh plugins
mkdir -p ~/.local/share/zsh/plugins
cd ~/.local/share/zsh/plugins
git clone https://github.com/zdharma-continuum/fast-syntax-highlighting
git clone https://github.com/zsh-users/zsh-completions
git clone https://github.com/zsh-users/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-history-substring-search

# Personal suckless terminal
echo -e "\nInstalling personal st..."
cd
git clone git@github.com:cohenchris/st
cd st
sudo make clean install
cd ../
rm -rf st/

################################################################################
#                                   MISC                                       #
################################################################################
# Download wallpapers
echo -e "\nDownloading wallpapers..."
git clone git@github.com:cohenchris/wallpapers ~/.local/wallpapers

# Delete extraneous XDG directories
echo -e "\nDeleting extraneous XDG directories..."
cd
rm -rf Desktop Documents Music Pictures Public Templates Videos

# npm config
echo -e "\nConfiguring NPM..."
sudo mkdir /usr/etc
echo "prefix=$HOME/.local/share/npm
cache=$HOME/.cache/npm
init-module=$HOME/.config/npm/config/npm-init.js" > npmrc
sudo mv npmrc /usr/etc/

# Replace notmuch config database path with whoever the $USER is
echo -e "\nConfiguring notmuch..."
sed -i "s/phrog/$USER/g" $HOME/.config/notmuch/config

# Start SSHD
echo -e "\nStarting SSHD..."
sudo systemctl enable sshd
sudo systemctl start sshd

# Start Docker
echo -e "\nStarting and Configuring Docker..."
sudo usermod -aG docker $USER
sudo systemctl enable docker
sudo systemctl start docker

echo -e "\n\nTime to reboot!"
