set nocompatible              " be iMproved, required
filetype off                  " required

set viminfo+=n${XDG_DATA_HOME}/vim/viminfo
set rtp+=${XDG_DATA_HOME}/vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'         " let Vundle manage Vundle, required
Plugin 'frazrepo/vim-rainbow'         " Vim-Rainbow - Paranthesis Color Coordination
Plugin 'lilydjwg/colorizer'           " Colorizer - Hex Color Visualization
Plugin 'itchyny/lightline.vim'        " Lightline - Status Bar
"Plugin 'valloric/youcompleteme'       " YouCompleteMe - Code Completion

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" For vim-rainbow plugin
let g:rainbow_active = 1
let g:rainbow_load_separately = [
    \ [ '*' , [['(', ')'], ['\[', '\]'], ['{', '}']] ],
    \ [ '*.tex' , [['(', ')'], ['\[', '\]']] ],
    \ [ '*.cpp' , [['(', ')'], ['\[', '\]'], ['{', '}']] ],
    \ [ '*.{html,htm}' , [['(', ')'], ['\[', '\]'], ['{', '}'], ['<\a[^>]*>', '</[^>]*>']] ],
    \ ]
let g:rainbow_guifgs = ['RoyalBlue3', 'DarkOrange3', 'DarkOrchid3', 'FireBrick']
let g:rainbow_ctermfgs = ['lightblue', 'lightgreen', 'yellow', 'red', 'magenta']

if has("syntax")
  syntax on
endif

set background=dark

filetype plugin indent on

set showcmd             " Show (partial) command in status line.
set showmatch           " Show matching brackets.
set ignorecase          " Do case insensitive matching
set smartcase           " Do smart case matching
set incsearch           " Incremental search
set autowrite           " Automatically save before commands like :next and :make
set hidden              " Hide buffers when they are abandoned
set mouse=a             " Enable mouse usage (all modes)
set number              " Line numbers
set noshowmode          "  ...
set nospell             " ...
set shellcmdflag=-ic    " ...
set termguicolors
set encoding=utf8
set laststatus=2

" redefine tabs as 2 spaces
set tabstop=2
set softtabstop=0 expandtab
set shiftwidth=2 smarttab


autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o    " disable auto-commenting on newline

" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"


let mapleader = " "
" <leader> + s   -->   spellchecker
:map <leader>s :setlocal spell!<CR>
" <leader> + c   -->   LaTeX compiler
:map <leader>c :!texcompile % & fg<CR><CR>
