#!/bin/bash

echo "********** WARNING ************"
read -p "CREATE A NEW BACKUP? (y/N) " yn

case $yn in
  [Yy]* ) ;;
  *     ) exit;;
esac

cd

export GPG_TTY=$(tty)
yadm encrypt
unset GPG_TTY

declare -a dotfiles=(
  ~/.config/dunst/
  ~/.config/foot/
  ~/.config/fuzzel/
  ~/.config/hypr/
  ~/.config/khal/
  ~/.config/khard/
  ~/.config/lf/
  ~/.config/mail/
  ~/.config/nvim/
  ~/.config/shell/
  ~/.config/user-dirs.dirs
  ~/.config/vdirsyncer/
  ~/.config/waybar/
  ~/.config/wget/
  ~/.config/yadm/
  ~/.config/zathura/
  ~/.local/backup/
  ~/.local/share/yadm/archive
  ~/.local/share/chars/
)

for i in ${dotfiles[@]}
do
  echo "----- UPLOADING $i -----"
  yadm add $i
done

curr_date=$(date +"%m-%d-%Y_%T")
yadm commit -m "backup $curr_date"
yadm push origin main
