#!/bin/bash

echo "********** WARNING ************"
read -p "CREATE A NEW BACKUP? (y/N) " yn

case $yn in
  [Yy]* ) ;;
  *     ) exit;;
esac

cd

export GPG_TTY=$(tty)
yadm encrypt
unset GPG_TTY

declare -a dotfiles=(
  ~/.config/dunst/
  ~/.config/git/
  ~/.config/i3/
  ~/.config/isync/
  ~/.config/khard/
  ~/.config/lf/
  ~/.config/neomutt/
  ~/.config/notifymuch/
  ~/.config/notmuch/
  ~/.config/nvim/init.vim
  ~/.config/polybar/
  ~/.config/python/
  ~/.config/shell/
  ~/.config/user-dirs.dirs
  ~/.config/vdirsyncer/config
  ~/.config/yadm/
  ~/.config/zathura/
  ~/.local/backup
  ~/.local/bin/personal
  ~/.local/share/yadm/archive
)

for i in ${dotfiles[@]}
do
  echo "----- UPLOADING $i -----"
  yadm add $i
done

curr_date=$(date +"%m-%d-%Y_%T")
yadm commit -m "backup $curr_date"
yadm push origin main
