#!/bin/bash

echo "********** WARNING ************"
read -p "CREATE A NEW BACKUP? (y/N) " yn

case $yn in
  [Yy]* ) ;;
  *     ) exit;;
esac

cd

declare -a dotfiles=(
  ~/.config/dunst/
  ~/.config/i3/
  ~/.config/polybar/
  ~/.config/ranger/
  ~/.config/yadm/
  ~/.config/alacritty/
  ~/.local/backup
  ~/.local/bin
  ~/.bashrc
  ~/.bash_profile
  ~/.gitconfig
  ~/.vimrc
)

for i in ${dotfiles[@]}
do
  echo "----- UPLOADING $i -----"
  yadm add $i
  echo
done

curr_date=$(date +"%m-%d-%Y_%T")
yadm commit -m "backup $curr_date"
yadm push origin main
