#!/bin/bash

echo "********** WARNING ************"
read -p "CREATE A NEW BACKUP? (y/N) " yn

case $yn in
  [Yy]* ) ;;
  *     ) exit;;
esac

# Save terminal settings
cd ~/.config/backup

cd

declare -a dotfiles=(
  ~/.config/backup
  ~/.config/bin
  ~/.config/dunst/
  ~/.config/i3/
  ~/.config/polybar/
  ~/.config/yadm/
  ~/.bashrc
  ~/.bash_profile
  ~/.gitconfig
  ~/.vimrc
  ~/Projects
)

for i in ${dotfiles[@]}
do
  echo "----- UPLOADING $i -----"
  yadm add $i
  echo
done

curr_date=$(date +"%m-%d-%Y_%T")
yadm commit -m "backup $curr_date"
yadm push origin main
