#!/bin/sh

# Press ctrl-x to use hotkeys
while read -r file
do

  case "$1" in
    "r")
      convert -rotate 90 "$file" "$file" ;;
    "R")
      convert -rotate -90 "$file" "$file" ;;
    "d")
      mkdir -p deleted && mv "$file" ./deleted && notify-send "$file deleted." ;;
  esac

done
