#!/bin/bash

bwChoice=$(echo -e "Username and Password\nUsername\nPassword" | dmenu -p "What should be entered?" -l 3 -nb "#1e1e1e" -sf "#aaff77" -sb "#333333" -nf "#ffffff")

case $bwChoice in
  "Username and Password")
    echo "spawn --userscript qute-bitwarden --dmenu-invocation='dmenu -p \"Select an entry:\" -nb \"#1e1e1e\" -sf \"#aaff77\" -sb \"#333333\" -nf \"#ffffff\" -l 10' --password-prompt-invocation='dmenu -p \"Enter master password:\" -lines 0 -nb \"#1e1e1e\" -sf \"#aaff77\" -sb \"#333333\" -nf \"#1e1e1e\"'" >> $QUTE_FIFO
    ;;
  
  "Username")
    echo "spawn --userscript qute-bitwarden --username-only --dmenu-invocation='dmenu -p \"Select an entry:\" -nb \"#1e1e1e\" -sf \"#aaff77\" -sb \"#333333\" -nf \"#ffffff\" -l 10' --password-prompt-invocation='dmenu -p \"Enter master password:\" -lines 0 -nb \"#1e1e1e\" -sf \"#aaff77\" -sb \"#333333\" -nf \"#1e1e1e\"'" >> $QUTE_FIFO
 nes   ;;

  "Password")
    echo "spawn --userscript qute-bitwarden --password-only --dmenu-invocation='dmenu -p \"Select an entry:\" -nb \"#1e1e1e\" -sf \"#aaff77\" -sb \"#333333\" -nf \"#ffffff\" -l 10' --password-prompt-invocation='dmenu -p \"Enter master password:\" -nb \"#1e1e1e\" -sf \"#aaff77\" -sb \"#333333\" -nf \"#1e1e1e\"'" >> $QUTE_FIFO
    ;;
esac


